//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent_info_list_item
    {
        public int ColId { get; set; }
        public int AgentID { get; set; }
        public string AgentName { get; set; }
        public string Password { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string SellerID { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string Account_status { get; set; }
        public byte[] Photo { get; set; }
        public string Photo_Type { get; set; }
        public string Email { get; set; }
    }
}
