//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class config_list_item
    {
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public string P_Value { get; set; }
    }
}
