//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class password_log_list_item
    {
        public int P_Id { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
    }
}
