//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class scrmEntities : DbContext
    {
        public scrmEntities()
            : base("name=scrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent_info_list_item> agentinfo { get; set; }
        public virtual DbSet<config_list_item> config { get; set; }
        public virtual DbSet<facebook_post_list_item> facebook_post { get; set; }
        public virtual DbSet<field_list_item> field { get; set; }
        public virtual DbSet<field_option_list_item> field_option { get; set; }
        public virtual DbSet<user_role_list_item> user_role { get; set; }
        public virtual DbSet<task_schedule_setting_list_item> task_schedule_setting { get; set; }
        public virtual DbSet<task_schedule_record_list_item> task_schedule_record { get; set; }
        public virtual DbSet<password_log_list_item> password_log { get; set; }
        public virtual DbSet<floor_plan_list_item> floor_plan { get; set; }
    
        public virtual ObjectResult<Nullable<int>> Restore_NP360()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Restore_NP360");
        }
    
        public virtual ObjectResult<Nullable<int>> Restore_HKTB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Restore_HKTB");
        }
    }
}
