//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_schedule_setting_list_item
    {
        public int S_Id { get; set; }
        public string Service { get; set; }
        public string Display_Message { get; set; }
        public string Schedule_Type { get; set; }
        public Nullable<System.DateTime> Schedule_Time { get; set; }
        public string Status { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Time { get; set; }
    }
}
