//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scrm1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role_list_item
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string Companies { get; set; }
        public string Categories { get; set; }
        public string Functions { get; set; }
        public string RoleStatus { get; set; }
    }
}
